import type { Step } from './bot';

/**
 * A sensible "decent player" build: arrows early, then splash for crowds, magic for iron,
 * True Sight before invisible rounds, a farm, then a late-game carry per damage type.
 */
export const STANDARD: Step[] = [
  { place: 'ranger', as: 'r1', maxFrac: 0.3 },
  { place: 'ranger', as: 'r2', maxFrac: 0.4 },
  { up: 'r1', path: 0, times: 2 },
  { up: 'r2', path: 0, times: 2 },
  { place: 'bombardier', as: 'b1' },
  { up: 'b1', path: 0, times: 2 },
  { place: 'ranger', as: 'r3' },
  { up: 'r3', path: 0, times: 2 },
  { place: 'wizard', as: 'w1' },
  { up: 'w1', path: 0, times: 2 },
  { up: 'r1', path: 0, times: 1 },
  { place: 'cleric', as: 'c1' },
  { up: 'c1', path: 1, times: 2 },
  { up: 'w1', path: 2, times: 2 },
  { place: 'treasury', as: 't1' },
  { place: 'rogue', as: 'g1', minFrac: 0.3, maxFrac: 0.7 },
  { up: 'g1', path: 0, times: 3 },
  { up: 'b1', path: 2, times: 2 },
  { place: 'druid', as: 'd1' },
  { up: 'd1', path: 1, times: 2 },
  { up: 'r2', path: 0, times: 1 },
  { up: 'r3', path: 1, times: 2 },
  { up: 'b1', path: 0, times: 1 },
  { up: 'w1', path: 0, times: 1 },
  { place: 'bombardier', as: 'b2' },
  { up: 'b2', path: 0, times: 3 },
  { up: 't1', path: 0, times: 2 },
  { place: 'wizard', as: 'w2' },
  { up: 'w2', path: 1, times: 3 },
  { up: 'w2', path: 0, times: 2 },
  { up: 'r1', path: 0, times: 1 },
  { up: 'c1', path: 0, times: 2 },
  { up: 'd1', path: 1, times: 1 },
  { up: 'b1', path: 0, times: 1 },
  { up: 'w1', path: 0, times: 1 },
  { up: 't1', path: 0, times: 1 },
  { place: 'cleric', as: 'c2', minFrac: 0.5 },
  { up: 'c2', path: 1, times: 1 },
  { up: 'g1', path: 0, times: 1 },
  { place: 'ballista', as: 'x1' },
  { up: 'x1', path: 0, times: 3 },
  { up: 'x1', path: 1, times: 2 },
  { up: 'w2', path: 1, times: 1 },
  { up: 'x1', path: 0, times: 1 },
  { place: 'fighter', as: 'f1' },
  { up: 'f1', path: 0, times: 4 },
  { up: 'f1', path: 1, times: 2 },
  { up: 'c1', path: 1, times: 2 },
  { up: 'd1', path: 1, times: 1 },
  { up: 'b1', path: 0, times: 1 },
  { up: 'w1', path: 0, times: 1 },
  { up: 'w2', path: 1, times: 1 },
  { up: 'x1', path: 0, times: 1 },
  { place: 'ballista', as: 'x2' },
  { up: 'x2', path: 0, times: 5 },
  { up: 'x2', path: 1, times: 2 },
  { up: 'f1', path: 0, times: 1 },
  { place: 'bombardier', as: 'b3' },
  { up: 'b3', path: 0, times: 5 },
  { up: 'b3', path: 1, times: 2 },
  { place: 'ranger', as: 'r4' },
  { up: 'r4', path: 1, times: 5 },
  { up: 'r4', path: 0, times: 2 },
];

/** A lazy build: a handful of lightly upgraded rangers. Should lose mid-game. */
export const WEAK: Step[] = [
  { place: 'ranger', as: 'r1' },
  { place: 'ranger', as: 'r2' },
  { up: 'r1', path: 0, times: 2 },
  { place: 'ranger', as: 'r3' },
  { up: 'r2', path: 0, times: 2 },
  { place: 'ranger', as: 'r4' },
];

/** An optimised build for Hard: early economy, layered True Sight and tier-5 carries per damage type. */
export const STRONG: Step[] = [
  { place: 'ranger', as: 'r1', maxFrac: 0.3 },
  { place: 'ranger', as: 'r2', maxFrac: 0.4 },
  { up: 'r1', path: 0, times: 2 },
  { up: 'r2', path: 0, times: 2 },
  { place: 'bombardier', as: 'b1' },
  { up: 'b1', path: 0, times: 2 },
  { place: 'treasury', as: 't1' },
  { up: 't1', path: 0, times: 2 },
  { place: 'wizard', as: 'w1' },
  { up: 'w1', path: 0, times: 2 },
  { place: 'cleric', as: 'c1' },
  { up: 'c1', path: 1, times: 2 },
  { up: 'r1', path: 0, times: 1 },
  { place: 'rogue', as: 'g1', minFrac: 0.3, maxFrac: 0.7 },
  { up: 'g1', path: 0, times: 3 },
  { up: 'b1', path: 2, times: 2 },
  { place: 'druid', as: 'd1' },
  { up: 'd1', path: 1, times: 3 },
  { place: 'treasury', as: 't2' },
  { up: 't2', path: 0, times: 2 },
  { up: 't1', path: 0, times: 1 },
  { up: 'w1', path: 2, times: 2 },
  { up: 'b1', path: 0, times: 1 },
  { up: 'w1', path: 0, times: 1 },
  { up: 't2', path: 0, times: 1 },
  { place: 'cleric', as: 'c2', minFrac: 0.5 },
  { up: 'c2', path: 1, times: 3 },
  { up: 'c2', path: 0, times: 2 },
  { place: 'ballista', as: 'x1' },
  { up: 'x1', path: 0, times: 4 },
  { up: 'x1', path: 1, times: 2 },
  { up: 't1', path: 0, times: 1 },
  { up: 'r1', path: 0, times: 1 },
  { up: 'g1', path: 0, times: 1 },
  { place: 'wizard', as: 'w2' },
  { up: 'w2', path: 1, times: 4 },
  { up: 'w2', path: 0, times: 2 },
  { up: 'b1', path: 0, times: 1 },
  { up: 'd1', path: 1, times: 1 },
  { up: 'c1', path: 1, times: 2 },
  { place: 'rogue', as: 'g2', minFrac: 0.6 },
  { up: 'g2', path: 1, times: 4 },
  { up: 'g2', path: 0, times: 2 },
  { up: 'x1', path: 0, times: 1 },
  { up: 'w1', path: 0, times: 1 },
  { up: 't2', path: 0, times: 1 },
  { place: 'ballista', as: 'x2' },
  { up: 'x2', path: 0, times: 5 },
  { up: 'x2', path: 1, times: 2 },
  { up: 'g2', path: 1, times: 1 },
  { up: 'w2', path: 1, times: 1 },
  { place: 'bombardier', as: 'b2' },
  { up: 'b2', path: 0, times: 5 },
  { up: 'b2', path: 1, times: 2 },
  { place: 'ballista', as: 'x3' },
  { up: 'x3', path: 0, times: 5 },
  { up: 'x3', path: 1, times: 2 },
  { place: 'fighter', as: 'f1' },
  { up: 'f1', path: 0, times: 5 },
  { up: 'f1', path: 1, times: 2 },
  { place: 'ballista', as: 'x4' },
  { up: 'x4', path: 0, times: 5 },
  { up: 'x4', path: 1, times: 2 },
];
